### ISSUE TITLE
Read info from Obj array

### ISSUE THREAD

**Issue by tomcohen** [shenkarlab/Tlushim#10]
@akariv  @mushon 

היי אדם,
איך אפשר לקרוא מידע (=להדפיסו למסך) של איבר ספציפי במערך של אוביקטים למשל:

```
var someArray = [{ name: Tom , family: Cohen} , {name: rotem , family: math}];
```

איך אני לוקח את האיבר הספציפי נניח השם הפרטי רותם ומדפיס אותו?

ניסיתי הרבה דברים למשל :

```
someArray[2].name
someArray[2].name.tostring()
```

לא עובד :(
תודה.

**Comment by akariv** [comment]
הקוד שצירפתם לא חוקי, הדרך הנכונה לכתוב היא זו:

```
var someArray = [{ name: "Tom" , family: "Cohen"} , {name: "rotem" , family: "math"}];
```

שנית, זה מערך עם שני איברים אז

```
 someArray[2] 
```

אינו מוגדר.

בהנחה שזה מה שעשתים וזו סתם טעות בהעתקה, אז בשביל להדפיס את הערך ב-
console
:אפשר להשתמש בקוד הבא

```
console.log(someArray[1].name)
```

**Comment by tomcohen** [comment]
זה טעות בכתיבה שלי פה, זה לא עבד לי כשניסיתי בקוד על המקום ה0
someArray[0]

console.log(someArray[1].name)
זה ידפיס לי את האמור לקונסול.
השאלה איך אני מדפיס נניח כחלק מHTML

**Comment by tomcohen** [comment]
@akariv  @mushon 

טוב התקדמתי קצת
זה מקבל את המידע מהCSV

```
     topInfo = d3.csv(data)    .row(function(d) { return {AverageSalary: d.AverageSalary, Job: d.Job, Organization: d.Organization, Data:d.Data}; })
         .get(function(error, rows) { console.log(rows); });


    console.log("this is row 1 " + topInfo.get(function(error, rows) { console.log(rows[1].Data); }));
```

כאשר אני מבצע את השורה האחרונה של ה
console.log
הוא מדפיס לי לקונסול בדיוק מה שאני רוצה.
אך שאני מנסה להדפיס את זה לHTML 
בשורה הבאה

```
.text("" + topInfo.get(function(error, rows) { (rows[id.x].Job) }));
```

אני מקבל
[Object,Object]
זה מה שהוא מדפיס.
בדקתי הוא מקבל x.id
כמו שצריך
וכן יש כזה משתנה JOB

**Comment by tomcohen** [comment]
Solved
