### ISSUE TITLE
Programming issues

### ISSUE THREAD

**Issue by tomcohen** [shenkarlab/Tlushim#3]

**Comment by mushon** [comment]
@akariv can you give them feedback here?

**Comment by rotman** [comment]
@akariv 
היי אדם,
אני מנסה לגרום לכך שבציר y
יהיה לי את שמות הדרגות (אנחנו משווים בין דרגות בצבא ובמשטרה)
הנה הקוד:
;;;
			d3.json("army2012.json", function(army_data) {
				d3.json("police2012.json", function(police_data) {

				//width and height of the svg	
				var w =800;
				var h = 600;
				var padding = 70;
									
				//Create svg
				var svg = d3.select("body").append("svg").attr("width", w).attr("height", h);
				var xScale = d3.scale.linear()
											.domain([0, d3.max(police_data, function(d) {return d.AverageSalary;})])
											.range([padding, w-padding]);
				var yScale = d3.scale.ordinal()
											.domain(police_data.map(function(d) {return d.Rank;}))
											.rangeBands([padding,h]);	
				
				var xAxis = d3.svg.axis()
							.scale(xScale)
						  	.orient("bottom")
							.ticks(5);	
								  
				var yAxis = d3.svg.axis()
						 .scale(yScale)
						 .orient("left")
						 .ticks(5);			
					
				//Create X axis
				svg.append("g")
					.attr("class", "x axis")
					.attr("transform", "translate(0," + (h - padding + 5) + ")")
					.call(xAxis);
		
				//Create Y axis
				svg.append("g")
					.attr("class", "y axis")
					.attr("transform", "translate(" + (padding - 5) + ",0)")
					.call(yAxis);
			});
		});
;;;
 מצורפת גם סקרין שוט של מה שיוצא מהקוד כרגע:
![screenshot 2015-01-04 16 27 46](https://cloud.githubusercontent.com/assets/9404718/5606262/36339764-942f-11e4-9d24-ab79b1c6d600.png)

מה שאני רוצה זה שתהיה דרגת מפכ"ל ומתחתיה רמטכ"ל ואז בציר X 
יהיו ברים שיגדלו כאורך המשכורת הממוצעת
ואז ניצב ומתחתיו אלוף וכדומה...

איך אני עושה את זה?

תודה!

**Comment by akariv** [comment]
הפתרון הנכון הוא כמובן להכין מראש את הקובץ ככה שיכיל את המידע מסודר בדיוק איך שאתם צריכים, כדי שלא תצטרכו להסתבך עם זה בזמן הציור...
אם הבנתי מה אמורה להיות התוצאה הסופית, יש להניח שאתם רוצים לשמור את המידע בצורה אחרת, בה יש לכם רשומה נפרדת לרמטכ״ל+מפכ״ל, ניצב+אלוף וכו׳.

**Comment by tomcohen** [comment]
@akariv  @mushon 
היי אדם,
http://shenkarlab.github.io/Tlushim/

בעמוד יש סליידר בצד שמאל
הוא חורג בגובה שלו (כרגע נתתי לו ערך אחד יותר גבוה והוא עומד במקום)
אבל אם מזיזים את הסמן שלו למעלה הוא חורג מגובה הסליידר

השאלה מה לעשות?
האם אפשר להגדיר טווח מסויים אבל להגביל לו את התנועה?
או פתרון אחר?

תודה

**Comment by akariv** [comment]
נראה שטווח התנועה של ה״ידית״ של הסליידר הוא בדיוק הגודל של הסליידר עצמו. כל
מה שאתם צריכים לעשות זה לסדר את ה-margin ים של הידית בשביל שתכוון למקום
הנכון (ז״א להוריד אותו בכמה פיקסלים).

אדם

**Comment by tomcohen** [comment]
ה
margin 
לא משפיע אדם.....
ישבתי על זה ככ הרבה לפני שפניתי אליך תאמין לי...
בטוח שאני מפספס משהו השאלה מה...

@akariv @mushon

**Comment by mushon** [comment]
```
a.ui-slider-handle{
  margin-bottom: -26px;
}
```

**Comment by tomcohen** [comment]
@mushon @akariv 

הסתדר המיקום קצת שונה..
 תודה מושון ואדם

**Comment by mushon** [comment]
@tomcohen & @rotman great!
Generally, it's good to separate bugs like these into separate issues so it's easier to track their status and to be able to get an overview of what's closed and what's open. I will now close this issue and if new ones come up I suggest you open a new issue, work on it between you guys and if you need our help, @mention us.

**Comment by mushon** [comment]
btw, I was about to send you to look at scales again to solve this the right way, so if it's still relevant I would suggest reading: http://alignedleft.com/tutorials/d3/scales/
