### ISSUE TITLE
get data from csv

### ISSUE THREAD

**Issue by rotman** [shenkarlab/Tlushim#9]
@akariv @mushon 
היי אדם,
אנחנו רוצים לקחת מידע מקובץ csv
לא הצלחנו ולא מצאנו שום באינטרנט שיכול לעזור.
האם אתה מכיר דרך?

תודה ושבת שלום

**Comment by akariv** [comment]
אפשר להשתמש ב-d3:

https://github.com/mbostock/d3/wiki/CSV

**Comment by tomcohen** [comment]
לא ממש הצלחתי לעבוד עם זה לכן באה השאלה

**Comment by akariv** [comment]
באופן כללי אני ממליץ להמיר את כל המידע ל-json מראש ולעבוד עם זה ולא עם
ה-CSV.

**Comment by tomcohen** [comment]
@akariv 
אדם כרגע אין לנו ברירה 
הכל כבר בCSV 
מסיבות שקשורות לגרפים

יש דרך אחרת לקבל את המידע מהCSV 
לתוך משתנה כלשהו נניח מערך שנוכל להמשיך לעבוד עליו?

לא חייב D3
גם פיתרון בJQUERY 
יהיה בסדר....

**Comment by tomcohen** [comment]
Solved
